---
title: "Pandas Placeholder"
subtitle: "A placeholder note for Pandas basics."
author: "Cam"
date: 2021-01-01
description: "A placeholder note for Pandas basics."
summary: "A placeholder note for Pandas basics."
type: note
categories: ["Python", "Pandas"]
tags: ["data science", "pandas"]
draft: false
---

{{< toc >}}

## Installation

To install `pip install pandas`

## Sample Dataframe

Here's a sample chart from the matplotlib gallery.

Note need to make table border one in custom css? remove scroll bars? then looks good...

In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df

     A   B   C   D
0   57  11  19  16
1   90  64   2  76
2   97  42  88   9
3   72  12  79  56
4   87  49  77  65
..  ..  ..  ..  ..
95  65  62  24  77
96  45  77  23  31
97  37  65  27  28
98  41  89  72  45
99  65   0  39  22

[100 rows x 4 columns]

In [12]:
display(df)

     A   B   C   D
0   57  11  19  16
1   90  64   2  76
2   97  42  88   9
3   72  12  79  56
4   87  49  77  65
..  ..  ..  ..  ..
95  65  62  24  77
96  45  77  23  31
97  37  65  27  28
98  41  89  72  45
99  65   0  39  22

[100 rows x 4 columns]

In [11]:
print(df.to_markdown())

|    |   A |   B |   C |   D |
|---:|----:|----:|----:|----:|
|  0 |  57 |  11 |  19 |  16 |
|  1 |  90 |  64 |   2 |  76 |
|  2 |  97 |  42 |  88 |   9 |
|  3 |  72 |  12 |  79 |  56 |
|  4 |  87 |  49 |  77 |  65 |
|  5 |  44 |  25 |  84 |  71 |
|  6 |  14 |   8 |  12 |  21 |
|  7 |  56 |  82 |  82 |  74 |
|  8 |  25 |   7 |  43 |  28 |
|  9 |  37 |  88 |  61 |  10 |
| 10 |   5 |   7 |  63 |  40 |
| 11 |  28 |  71 |  80 |  95 |
| 12 |  31 |  29 |  63 |  77 |
| 13 |  88 |  69 |  87 |  47 |
| 14 |  96 |  73 |  46 |  64 |
| 15 |  74 |  94 |  64 |  63 |
| 16 |   4 |   4 |  20 |  60 |
| 17 |  70 |  68 |   6 |   0 |
| 18 |  26 |  10 |  95 |  65 |
| 19 |   8 |  80 |  94 |   2 |
| 20 |  94 |  13 |  60 |  97 |
| 21 |  26 |  41 |  29 |  69 |
| 22 |  73 |  13 |  21 |  93 |
| 23 |  41 |  46 |   7 |  86 |
| 24 |  82 |  44 |  50 |  76 |
| 25 |  29 |  13 |  66 |  16 |
| 26 |  31 |  35 |  36 |  22 |
| 27 |   1 |  12 |  12 |  42 |
| 28 |  26 |  69 |  19 |  89 |
| 29 |  35 |  29 |  16 |   4 |
| 30 |  60 |  98 |  11 |  10 |
| 31 |  79 |  96 |  35 |  45 |
| 32 |  75 |  44 |  27 |  54 |
| 33 |  73 |  13 |  62 |  70 |
| 34 |  70 |  39 |  37 |  19 |
| 35 |  77 |  32 |  35 |  44 |
| 36 |  14 |  96 |  51 |  17 |
| 37 |  82 |  68 |   6 |  62 |
| 38 |  84 |  65 |  15 |   9 |
| 39 |   0 |  48 |  99 |  33 |
| 40 |  45 |  86 |   7 |  61 |
| 41 |  45 |  25 |  44 |  25 |
| 42 |  70 |  76 |  60 |  79 |
| 43 |  40 |  48 |  24 |  54 |
| 44 |  79 |  99 |  45 |  78 |
| 45 |   5 |  52 |   9 |  48 |
| 46 |  82 |  79 |  62 |  16 |
| 47 |  20 |   0 |  42 |  51 |
| 48 |  27 |  69 |   4 |  94 |
| 49 |  76 |  65 |  10 |   9 |
| 50 |  17 |  61 |  68 |  62 |
| 51 |  51 |  42 |   4 |  58 |
| 52 |  77 |  61 |  28 |  49 |
| 53 |  16 |  33 |  25 |  46 |
| 54 |  19 |  98 |  49 |  79 |
| 55 |  63 |   1 |  70 |  25 |
| 56 |  78 |  72 |  68 |  68 |
| 57 |  14 |  76 |  81 |  11 |
| 58 |   5 |  11 |  88 |  73 |
| 59 |  73 |  76 |  50 |  64 |
| 60 |  35 |  88 |  64 |  81 |
| 61 |  74 |  16 |  17 |  50 |
| 62 |  79 |  14 |  54 |  47 |
| 63 |  17 |   1 |  29 |   6 |
| 64 |  93 |  57 |  43 |  77 |
| 65 |   5 |  39 |   8 |  37 |
| 66 |  88 |  25 |  80 |  44 |
| 67 |  44 |  74 |  55 |  85 |
| 68 |  85 |  81 |  10 |  11 |
| 69 |   7 |  74 |  83 |  42 |
| 70 |  40 |  81 |  37 |  45 |
| 71 |  49 |   1 |  71 |  35 |
| 72 |   4 |  41 |  89 |  41 |
| 73 |  31 |  13 |  55 |  72 |
| 74 |  49 |  95 |  72 |  10 |
| 75 |  63 |  69 |  91 |  42 |
| 76 |  79 |  28 |  65 |  34 |
| 77 |  34 |  81 |  45 |  92 |
| 78 |   1 |  44 |  40 |  40 |
| 79 |  90 |  26 |  37 |  57 |
| 80 |   1 |  95 |   5 |  18 |
| 81 |  67 |  50 |  45 |  16 |
| 82 |   2 |  41 |  42 |  79 |
| 83 |  75 |   5 |  15 |  82 |
| 84 |  29 |  78 |  43 |   8 |
| 85 |  91 |   8 |  97 |  39 |
| 86 |  77 |  48 |  93 |  18 |
| 87 |  91 |  15 |  31 |  80 |
| 88 |  49 |  59 |  68 |  60 |
| 89 |  31 |  55 |  55 |  90 |
| 90 |  59 |   4 |   6 |  89 |
| 91 |   2 |   6 |  90 |   0 |
| 92 |  49 |  16 |  77 |  64 |
| 93 |   3 |  17 |  70 |  65 |
| 94 |  28 |  83 |   8 |  75 |
| 95 |  65 |  62 |  24 |  77 |
| 96 |  45 |  77 |  23 |  31 |
| 97 |  37 |  65 |  27 |  28 |
| 98 |  41 |  89 |  72 |  45 |
| 99 |  65 |   0 |  39 |  22 |

## References

- [venv Docs](https://docs.python.org/3/library/venv.html)
- [IPython Docs](https://ipython.readthedocs.io/en/stable/install/kernel_install.html)

In [10]:
#Versions used in this notebook
import sys
print("OS:", sys.platform)

!python --version

from importlib.metadata import version
for library in ["jupyterlab", "pandas", "numpy"]:
    print(library, version(library))

OS: win32
Python 3.9.1
jupyterlab 2.2.0
pandas 1.2.0
numpy 1.19.5